//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReserVA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recinto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recinto()
        {
            this.Espacio = new HashSet<Espacio>();
        }
    
        public int IdRecinto { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int IdSubzona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Espacio> Espacio { get; set; }
        public virtual Subzona Subzona { get; set; }
    }
}
