//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RerserVA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subzona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subzona()
        {
            this.Recinto = new HashSet<Recinto>();
        }
    
        public int IdSubzona { get; set; }
        public int IdBarrio { get; set; }
        public int CodigoSubzona { get; set; }
        public string Nombre { get; set; }
    
        public virtual Barrio Barrio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recinto> Recinto { get; set; }
    }
}
