//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReserVA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsoEspecifico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsoEspecifico()
        {
            this.UsoEspacio = new HashSet<UsoEspacio>();
        }
    
        public int IdUsoEspecifico { get; set; }
        public int IdUsoGeneral { get; set; }
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsoEspacio> UsoEspacio { get; set; }
        public virtual UsoGeneral UsoGeneral { get; set; }
    }
}
